import { Trade, User, CapitalTransaction } from './types';

export const mockUser: User = {
    id: 'u1',
    email: 'trader@tradeedge.com',
    name: 'Ahmad Rizal',
    plan: 'pro',
    trialEnd: '2026-03-16',
    createdAt: '2026-03-01',
};

export const mockTrades: Trade[] = [
    {
        id: 't1',
        userId: 'u1',
        ticker: 'TOPGLOV',
        market: 'bursa',
        strategy: 'swing',
        status: 'closed',
        buyDate: '2026-02-10',
        buyTime: '09:15',
        sellDate: '2026-02-18',
        sellTime: '14:30',
        buyPrice: 1.05,
        sellPrice: 1.22,
        quantity: 10000,
        capitalUsed: 10500,
        fees: 42,
        stopLoss: 0.98,
        takeProfit1: 1.20,
        takeProfit2: 1.35,
        setupSource: 'Breakout above resistance',
        entryThesis: 'Strong volume breakout above RM1.05 resistance with MACD crossover. Rubber glove sector showing renewed interest.',
        exitReason: 'Hit TP1 at RM1.20, trailed stop to RM1.18, closed at RM1.22 on pullback signal.',
        emotionEntry: 'confident',
        emotionExit: 'calm',
        lessons: 'Good discipline on trailing stop. Could have held partial for TP2.',
        tags: ['breakout', 'glove', 'momentum'],
        createdAt: '2026-02-10T09:20:00Z',
    },
    {
        id: 't2',
        userId: 'u1',
        ticker: 'AAPL',
        market: 'us',
        strategy: 'swing',
        status: 'closed',
        buyDate: '2026-02-05',
        buyTime: '21:35',
        sellDate: '2026-02-14',
        sellTime: '22:00',
        buyPrice: 228.50,
        sellPrice: 235.80,
        quantity: 20,
        capitalUsed: 4570,
        fees: 2.50,
        stopLoss: 222.00,
        takeProfit1: 235.00,
        takeProfit2: 242.00,
        setupSource: 'Support bounce + earnings catalyst',
        entryThesis: 'AAPL bouncing off 50-day MA with upcoming product event. RSI recovering from oversold.',
        exitReason: 'Hit TP1 target area, took profits ahead of FOMC.',
        emotionEntry: 'calm',
        emotionExit: 'confident',
        lessons: 'Good timing on entry. Exiting before FOMC was smart risk management.',
        tags: ['support-bounce', 'tech', 'earnings'],
        createdAt: '2026-02-05T21:40:00Z',
    },
    {
        id: 't3',
        userId: 'u1',
        ticker: 'GAMUDA',
        market: 'bursa',
        strategy: 'swing',
        status: 'closed',
        buyDate: '2026-01-20',
        buyTime: '10:00',
        sellDate: '2026-02-03',
        sellTime: '15:45',
        buyPrice: 5.80,
        sellPrice: 5.55,
        quantity: 2000,
        capitalUsed: 11600,
        fees: 46,
        stopLoss: 5.50,
        takeProfit1: 6.20,
        takeProfit2: 6.50,
        setupSource: 'Infrastructure play thesis',
        entryThesis: 'Government infrastructure spending narrative. Chart looked like accumulation phase.',
        exitReason: 'Hit stop loss after unexpected sector rotation out of construction.',
        emotionEntry: 'excited',
        emotionExit: 'frustrated',
        lessons: 'Entered too early on narrative alone. Wait for technical confirmation before entering on fundamentals.',
        tags: ['infra', 'construction', 'narrative'],
        createdAt: '2026-01-20T10:05:00Z',
    },
    {
        id: 't4',
        userId: 'u1',
        ticker: 'NVDA',
        market: 'us',
        strategy: 'intraday',
        status: 'closed',
        buyDate: '2026-02-20',
        buyTime: '22:30',
        sellDate: '2026-02-20',
        sellTime: '23:45',
        buyPrice: 890.00,
        sellPrice: 912.50,
        quantity: 5,
        capitalUsed: 4450,
        fees: 1.50,
        stopLoss: 878.00,
        takeProfit1: 905.00,
        takeProfit2: 920.00,
        setupSource: 'Earnings beat momentum',
        entryThesis: 'NVDA beat earnings estimates. Gap up with strong volume. Entered on first pullback to VWAP.',
        exitReason: 'Scaled out between TP1 and TP2. Closed before end of session.',
        emotionEntry: 'excited',
        emotionExit: 'confident',
        lessons: 'Intraday earnings plays can be very profitable but need to manage position size. This was a textbook setup.',
        tags: ['earnings', 'momentum', 'AI', 'intraday'],
        createdAt: '2026-02-20T22:35:00Z',
    },
    {
        id: 't5',
        userId: 'u1',
        ticker: 'CIMB',
        market: 'bursa',
        strategy: 'swing',
        status: 'closed',
        buyDate: '2026-02-01',
        buyTime: '09:30',
        sellDate: '2026-02-12',
        sellTime: '11:00',
        buyPrice: 7.85,
        sellPrice: 7.60,
        quantity: 1000,
        capitalUsed: 7850,
        fees: 31,
        stopLoss: 7.50,
        takeProfit1: 8.20,
        takeProfit2: 8.50,
        setupSource: 'Banking sector rotation',
        entryThesis: 'Expected bank sector rotation with BNM rate decision. CIMB near support.',
        exitReason: 'Cut loss as BNM held rates unchanged. Thesis invalidated.',
        emotionEntry: 'anxious',
        emotionExit: 'calm',
        lessons: 'Do not enter trades based solely on macro expectations. Wait for price confirmation.',
        tags: ['banking', 'macro', 'rate-decision'],
        createdAt: '2026-02-01T09:35:00Z',
    },
    {
        id: 't6',
        userId: 'u1',
        ticker: 'TSLA',
        market: 'us',
        strategy: 'intraday',
        status: 'closed',
        buyDate: '2026-02-25',
        buyTime: '22:00',
        sellDate: '2026-02-25',
        sellTime: '03:30',
        buyPrice: 340.00,
        sellPrice: 328.00,
        quantity: 10,
        capitalUsed: 3400,
        fees: 2.00,
        stopLoss: 332.00,
        takeProfit1: 355.00,
        takeProfit2: 365.00,
        setupSource: 'FOMO on momentum',
        entryThesis: 'TSLA was running. Entered late chasing momentum without proper setup.',
        exitReason: 'Hit stop loss. Reversed sharply after entering at day high.',
        emotionEntry: 'fomo',
        emotionExit: 'frustrated',
        lessons: 'Classic FOMO entry. Never chase. Wait for pullback or pass on the trade entirely.',
        tags: ['fomo', 'chase', 'lesson'],
        createdAt: '2026-02-25T22:05:00Z',
    },
    {
        id: 't7',
        userId: 'u1',
        ticker: 'MAYBANK',
        market: 'bursa',
        strategy: 'swing',
        status: 'open',
        buyDate: '2026-02-25',
        buyTime: '09:05',
        sellDate: '',
        sellTime: '',
        buyPrice: 10.20,
        sellPrice: 0,
        quantity: 500,
        capitalUsed: 5100,
        fees: 20,
        stopLoss: 9.80,
        takeProfit1: 10.80,
        takeProfit2: 11.20,
        setupSource: 'Dividend play + support bounce',
        entryThesis: 'Maybank near strong support at RM10.10-10.20. Ex-dividend coming. Historically bounces from this zone.',
        exitReason: '',
        emotionEntry: 'calm',
        emotionExit: 'neutral',
        lessons: '',
        tags: ['dividend', 'banking', 'support'],
        createdAt: '2026-02-25T09:10:00Z',
    },
    {
        id: 't8',
        userId: 'u1',
        ticker: 'MSFT',
        market: 'us',
        strategy: 'swing',
        status: 'open',
        buyDate: '2026-02-26',
        buyTime: '21:45',
        sellDate: '',
        sellTime: '',
        buyPrice: 415.00,
        sellPrice: 0,
        quantity: 8,
        capitalUsed: 3320,
        fees: 2.00,
        stopLoss: 400.00,
        takeProfit1: 435.00,
        takeProfit2: 450.00,
        setupSource: 'Cloud earnings momentum',
        entryThesis: 'MSFT Azure growth exceeding expectations. Pullback to 20-day MA provides good entry.',
        exitReason: '',
        emotionEntry: 'confident',
        emotionExit: 'neutral',
        lessons: '',
        tags: ['cloud', 'tech', 'earnings-follow'],
        createdAt: '2026-02-26T21:50:00Z',
    },
    {
        id: 't9',
        userId: 'u1',
        ticker: 'INARI',
        market: 'bursa',
        strategy: 'intraday',
        status: 'closed',
        buyDate: '2026-02-27',
        buyTime: '09:10',
        sellDate: '2026-02-27',
        sellTime: '14:50',
        buyPrice: 3.15,
        sellPrice: 3.28,
        quantity: 5000,
        capitalUsed: 15750,
        fees: 63,
        stopLoss: 3.08,
        takeProfit1: 3.25,
        takeProfit2: 3.35,
        setupSource: 'Semiconductor cycle play',
        entryThesis: 'INARI gap up on US semicon positive sentiment overnight. Volume surge at open.',
        exitReason: 'Took profits above TP1 as momentum faded in afternoon session.',
        emotionEntry: 'confident',
        emotionExit: 'calm',
        lessons: 'Good discipline. Entered on gap with volume confirmation. Exited when momentum faded. Textbook.',
        tags: ['semiconductor', 'gap-up', 'momentum', 'intraday'],
        createdAt: '2026-02-27T09:15:00Z',
    },
    {
        id: 't10',
        userId: 'u1',
        ticker: 'AMZN',
        market: 'us',
        strategy: 'swing',
        status: 'closed',
        buyDate: '2026-01-28',
        buyTime: '22:10',
        sellDate: '2026-02-10',
        sellTime: '22:30',
        buyPrice: 198.50,
        sellPrice: 210.20,
        quantity: 15,
        capitalUsed: 2977.50,
        fees: 2.00,
        stopLoss: 192.00,
        takeProfit1: 208.00,
        takeProfit2: 218.00,
        setupSource: 'AWS growth + breakout',
        entryThesis: 'AMZN breaking out of consolidation. AWS revenue beat driving institutional interest.',
        exitReason: 'Sold above TP1 after strong rally. Locking profits.',
        emotionEntry: 'calm',
        emotionExit: 'confident',
        lessons: 'Held through minor dips - patience paid off. AWS thesis was right.',
        tags: ['breakout', 'cloud', 'tech'],
        createdAt: '2026-01-28T22:15:00Z',
    },
    {
        id: 't11',
        userId: 'u1',
        ticker: 'TENAGA',
        market: 'bursa',
        strategy: 'swing',
        status: 'open',
        buyDate: '2026-02-28',
        buyTime: '09:30',
        sellDate: '',
        sellTime: '',
        buyPrice: 14.50,
        sellPrice: 0,
        quantity: 300,
        capitalUsed: 4350,
        fees: 17,
        stopLoss: 13.80,
        takeProfit1: 15.30,
        takeProfit2: 16.00,
        setupSource: 'Utility sector defensive play',
        entryThesis: 'Market volatility increasing. Tenaga as defensive play with stable dividend yield.',
        exitReason: '',
        emotionEntry: 'calm',
        emotionExit: 'neutral',
        lessons: '',
        tags: ['utility', 'defensive', 'dividend'],
        createdAt: '2026-02-28T09:35:00Z',
    },
    {
        id: 't12',
        userId: 'u1',
        ticker: 'GENM',
        market: 'bursa',
        strategy: 'swing',
        status: 'closed',
        buyDate: '2026-02-15',
        buyTime: '10:15',
        sellDate: '2026-02-22',
        sellTime: '11:30',
        buyPrice: 2.85,
        sellPrice: 3.02,
        quantity: 5000,
        capitalUsed: 14250,
        fees: 57,
        stopLoss: 2.72,
        takeProfit1: 3.00,
        takeProfit2: 3.15,
        setupSource: 'Tourism recovery thesis',
        entryThesis: 'Genting Malaysia showing recovery patterns with Chinese tourist inflow. Broke above 2.80 resistance.',
        exitReason: 'Closed slightly above TP1. Volume fading, took profits.',
        emotionEntry: 'confident',
        emotionExit: 'calm',
        lessons: 'Tourism thesis playing out. Should look for re-entry on pullback.',
        tags: ['tourism', 'recovery', 'breakout'],
        createdAt: '2026-02-15T10:20:00Z',
    },
    {
        id: 'p1',
        userId: 'u1',
        ticker: 'PAPER-AAPL',
        market: 'paper',
        strategy: 'swing',
        status: 'closed',
        buyDate: '2026-02-10',
        buyTime: '21:30',
        sellDate: '2026-02-17',
        sellTime: '22:00',
        buyPrice: 230.00,
        sellPrice: 238.00,
        quantity: 10,
        capitalUsed: 2300,
        fees: 0,
        stopLoss: 224.00,
        takeProfit1: 237.00,
        takeProfit2: 244.00,
        setupSource: 'Testing swing strategy on AAPL',
        entryThesis: 'Paper trading to test new swing setup using 20/50 MA crossover.',
        exitReason: 'TP1 hit. Strategy validated.',
        emotionEntry: 'neutral',
        emotionExit: 'neutral',
        lessons: 'Strategy works well on trending stocks. Need to test on choppy markets too.',
        tags: ['paper', 'strategy-test', 'MA-crossover'],
        createdAt: '2026-02-10T21:35:00Z',
    },
    {
        id: 'p2',
        userId: 'u1',
        ticker: 'PAPER-TOPGLOV',
        market: 'paper',
        strategy: 'intraday',
        status: 'open',
        buyDate: '2026-02-28',
        buyTime: '09:30',
        sellDate: '',
        sellTime: '',
        buyPrice: 1.18,
        sellPrice: 0,
        quantity: 20000,
        capitalUsed: 23600,
        fees: 0,
        stopLoss: 1.12,
        takeProfit1: 1.25,
        takeProfit2: 1.32,
        setupSource: 'Testing intraday breakout strategy',
        entryThesis: 'Paper trading intraday breakout on glove sector. Testing volume-based entry.',
        exitReason: '',
        emotionEntry: 'neutral',
        emotionExit: 'neutral',
        lessons: '',
        tags: ['paper', 'intraday-test', 'breakout'],
        createdAt: '2026-02-28T09:35:00Z',
    },
];

export const mockCapitalTransactions: CapitalTransaction[] = [
    {
        id: 'cap1',
        userId: 'u1',
        type: 'deposit',
        account: 'cds',
        amount: 30000,
        date: '2026-01-05',
        reference: 'FPX-20260105-001',
        note: 'Initial deposit to CDS account via Maybank',
        createdAt: '2026-01-05T10:00:00Z',
    },
    {
        id: 'cap2',
        userId: 'u1',
        type: 'deposit',
        account: 'brokerage_us',
        amount: 5000,
        date: '2026-01-08',
        reference: 'WIRE-20260108-001',
        note: 'Initial deposit to US brokerage (IBKR)',
        createdAt: '2026-01-08T14:00:00Z',
    },
    {
        id: 'cap3',
        userId: 'u1',
        type: 'deposit',
        account: 'cds',
        amount: 15000,
        date: '2026-01-25',
        reference: 'FPX-20260125-001',
        note: 'Top-up after month-end salary',
        createdAt: '2026-01-25T09:30:00Z',
    },
    {
        id: 'cap4',
        userId: 'u1',
        type: 'deposit',
        account: 'brokerage_us',
        amount: 3000,
        date: '2026-02-03',
        reference: 'WIRE-20260203-001',
        note: 'Additional US capital for tech opportunities',
        createdAt: '2026-02-03T11:00:00Z',
    },
    {
        id: 'cap5',
        userId: 'u1',
        type: 'withdrawal',
        account: 'cds',
        amount: 5000,
        date: '2026-02-15',
        reference: 'WD-20260215-001',
        note: 'Partial withdrawal for personal expenses',
        createdAt: '2026-02-15T16:00:00Z',
    },
    {
        id: 'cap6',
        userId: 'u1',
        type: 'deposit',
        account: 'cds',
        amount: 10000,
        date: '2026-02-25',
        reference: 'FPX-20260225-001',
        note: 'February salary top-up',
        createdAt: '2026-02-25T08:45:00Z',
    },
];
